version: '3'
services:
  web:
    image: web_modsecu  
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "80:80"
    depends_on:
      - mariadb_server
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      DB_SERVER: "mariadb_server"   
      DB_DATABASE: "web_tuyendung"
      DB_USER: "ankan"
      DB_PASSWORD: "310102"
    restart: always
    volumes:
      # Bind mounts
      - "./src/WEB:/var/www/html" 
      - "./src/ca/ca.crt:/etc/filebeat/ca.crt" 
      - "./src/ca/ca.crt:/etc/packetbeat/ca.crt"
      - "./startupCMDdocker.sh:/startupCMDdocker.sh"
      
      # Named volumes
      - "ModSecurity_data:/ModSecurity"  
      - "ModSecurity-apache_data:/ModSecurity-apache"
      - "confModsecurity_data:/etc/apache2/modsecurity.d"
      - "confModsecurity_data_apache:/etc/apache2/sites-available"
      - "filebeat_data:/etc/filebeat"

    extra_hosts:
      - "kibana.local:192.168.226.129"
      - "elasticsearch.local:192.168.226.129"
      - "logstash.local:192.168.226.129"

  mariadb_server:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: web_tuyendung
      MYSQL_USER: ankan
      MYSQL_PASSWORD: "310102"
    volumes:
      - db_data:/var/lib/mysql
      - "./initWebTD.sql:/docker-entrypoint-initdb.d/initWebTD.sql"
      - "./my_custom.cnf:/etc/mysql/mariadb.conf.d/99-custom.cnf"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb_server
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "81:80"
    depends_on:
      - mariadb_server
    restart: always

volumes:
  db_data:
  ModSecurity_data:
  ModSecurity-apache_data:
  confModsecurity_data:
  confModsecurity_data_apache:
  filebeat_data:
